services:
#  app:
#    build:
#        context: .
#        dockerfile: /backend/src/app/Dockerfile
#    env_file:
#      - .env
#    restart: always
#    ports:
#      - "8000:8000"
#    networks:
#      - storasense-network
#    depends_on:
#      - timescaledb

#  mqtt-client:
#    build:
#        context: .
#        dockerfile: ./backend/src/mqtt_client/Dockerfile
#    restart: always
#    networks:
#        - storasense-network

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - storasense_data_volume:/var/lib/postgresql/data
    networks:
      - storasense-network

volumes:
  storasense_data_volume:

networks:
  storasense-network:
    driver: bridge
