version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "5555:5555"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - HOST=${HOST}
      - PORT=${PORT}
    volumes:
      - .:/app
    networks:
        - storasense-platform-network

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
        - storasense-platform-network

volumes:
  timescale_data:

networks:
  storasense-platform-network:
    driver: bridge
