  services:
    mqtt-client:
      image: ghcr.io/storasense/storasense-platform/storasense-backend-mqtt-client:latest
      env_file: .env
      restart: on-failure
      networks:
        - storasense-network
      depends_on:
        - app
