from enum import Enum


class UserRole(Enum):
    ADMIN = "ADMIN"
    CONTRIBUTOR = "CONTRIBUTOR"


class SensorType(Enum):
    TEMPERATURE_INSIDE = "TEMPERATURE_INSIDE"
    TEMPERATURE_OUTSIDE = "TEMPERATURE_OUTSIDE"
    HUMIDITY = "HUMIDITY"
    GAS = "CO2"
    ULTRASONIC = "ULTRASONIC"


class MeasurementUnit(Enum):
    CELSIUS = "CELSIUS"
    PERCENT = "PERCENT"
    CENTIMETER = "CENTIMETER"
    PPM = "PPM"
