name: Deploy MkDocs

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install
        working-directory: docs

      - name: Build and Deploy MkDocs
        run: poetry run mkdocs gh-deploy --force
        working-directory: ./docs/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
